# Generated by Django 4.2.3 on 2023-09-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyBoardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(default='Level', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typer.keyboardlayout'),
            preserve_default=False,
        ),
    ]
