# Generated by Django 4.2.3 on 2023-09-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0002_keyboardlayout_level_name_level_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typer.keyboardlayout'),
        ),
    ]
